# Generated by Django 3.2 on 2023-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumplan', '0003_createplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createplan',
            name='user',
        ),
        migrations.AlterField(
            model_name='createplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
