# Generated by Django 3.2 on 2023-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiumplan', '0004_auto_20230417_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='createplan',
            name='status',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=10),
        ),
    ]
