# Generated by Django 3.2 on 2023-04-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypto_signal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forex_signal',
        ),
    ]
