# Generated by Django 3.2 on 2023-04-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20230413_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_signal_crypto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_signal_forex',
        ),
    ]
