# Generated by Django 3.2 on 2023-04-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createsignal', '0001_initial'),
        ('register', '0005_auto_20230413_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_signal_crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createsignal.cryptosignal'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_signal_forex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createsignal.forexsignal'),
        ),
    ]
