# Generated by Django 3.2 on 2023-04-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20230413_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_signal_crypto',
            new_name='winrate_crypto',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='total_signal_forex',
            new_name='winrate_forex',
        ),
    ]
