# Generated by Django 3.2 on 2023-04-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20230417_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
