# Generated by Django 3.2 on 2023-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_watch', models.CharField(choices=[(0, 'EURUSD'), (1, 'EURCHF'), (2, 'EURGBP'), (3, 'EURJPY'), (4, 'EURAUD'), (5, 'EURNZD'), (6, 'EURCAD'), (7, 'USDJPY'), (8, 'USDCAD'), (9, 'USDCHF'), (10, 'CADCHF'), (11, 'CADJPY'), (12, 'CHFJPY'), (13, 'GBPJPY'), (14, 'GBPCHF'), (15, 'GBPUSD'), (16, 'GBPNZD'), (17, 'GBPAUD'), (18, 'GBPCAD'), (19, 'AUDUSD'), (20, 'AUDCAD'), (21, 'AUDCHF'), (22, 'AUDJPY'), (23, 'AUDNZD'), (24, 'NZDUSD'), (25, 'NZDCAD'), (26, 'NZDCHF'), (27, 'NZDJPY'), (28, 'XAUUSD')], max_length=20)),
                ('live_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signal_type', models.CharField(choices=[(1, 'sell'), (2, 'buy'), (3, 'sell limit'), (4, 'sell stop'), (5, 'buy limit '), (6, 'buy stop')], max_length=25)),
                ('entry_price', models.IntegerField(blank=True, default=0, null=True)),
                ('take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('stop_loss', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_winrate', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_signal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forex_winrate', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_signal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
