# Generated by Django 3.2 on 2023-04-14 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createsignal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptosignal',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forexsignal',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register.user'),
            preserve_default=False,
        ),
    ]
