# Generated by Django 3.2 on 2023-04-16 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20230416_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createsignal', '0002_auto_20230414_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsignal',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptosignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='forexsignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.userprofile'),
        ),
    ]
